import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import vue from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'

export default [
  {
    ignores: [
      '.nuxt/**',
      '.output/**',
      'node_modules/**',
      'test-results/**',
      'playwright-report/**',
      'app/generated/**',
      'reference/**',
      'scripts/*.cjs',
      'scripts/fix-*.py',
      'scripts/import-data.ts',
      'scripts/import-to-db.ts',
      'scripts/import-xyq-downloads.ts',
      'scripts/generate-line-arts.ts',
      'scripts/generate-tips.ts',
      'scripts/restore-line-art.ts',
      'tmp-line-art-sheets/**',
      'backups/**',
      'public/line-arts/**',
      'docs/source/ac/**',
      'docs/archive/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...vue.configs['flat/recommended'],
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.vue'],
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
  },
  {
    files: ['**/*.{js,cjs,mjs,ts,vue}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearInterval: 'readonly',
        FormData: 'readonly',
        File: 'readonly',
        defineNuxtConfig: 'readonly',
        defineNuxtPlugin: 'readonly',
        defineEventHandler: 'readonly',
        createError: 'readonly',
        getCookie: 'readonly',
        setCookie: 'readonly',
        deleteCookie: 'readonly',
        getMethod: 'readonly',
        getRequestURL: 'readonly',
        getRouterParam: 'readonly',
        readBody: 'readonly',
        readMultipartFormData: 'readonly',
        useRuntimeConfig: 'readonly',
        useState: 'readonly',
        readonly: 'readonly',
        computed: 'readonly',
        ref: 'readonly',
        watch: 'readonly',
        watchEffect: 'readonly',
        onMounted: 'readonly',
        onUnmounted: 'readonly',
        useRoute: 'readonly',
        useRouter: 'readonly',
        definePageMeta: 'readonly',
        defineProps: 'readonly',
        defineEmits: 'readonly',
        $fetch: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        SVGSVGElement: 'readonly',
        MouseEvent: 'readonly',
        Event: 'readonly',
        HTMLInputElement: 'readonly',
        crypto: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        nextTick: 'readonly',
        navigateTo: 'readonly',
        safeJsonParse: 'readonly',
        useApi: 'readonly',
        useAuth: 'readonly',
        useDarkMode: 'readonly',
        useMockData: 'readonly',
        useNavItems: 'readonly',
        useSidebar: 'readonly',
        prisma: 'readonly',
        requireAuth: 'readonly',
        requireAdmin: 'readonly',
        verifyAuthToken: 'readonly',
        assertProductionAuthConfig: 'readonly',
        aiChat: 'readonly',
        getEffectiveAIConfig: 'readonly',
        xyqSubmitRun: 'readonly',
        xyqPollResult: 'readonly',
        createJob: 'readonly',
        getJob: 'readonly',
        findJobByIngredientId: 'readonly',
        startPolling: 'readonly',
      },
    },
    rules: {
      'no-undef': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-require-imports': 'off',
      'no-console': 'off',
      'no-empty': 'off',
      'no-useless-assignment': 'off',
      'no-useless-escape': 'off',
      'prefer-const': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-v-html': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/first-attribute-linebreak': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/no-template-shadow': 'off',
    },
  },
]
